# Stock prices dataset
The data is of tock exchange's stock listings for each trading day of 2010 to 2016.

## Description
A brief description of columns.
- open: The opening market price of the equity symbol on the date
- high: The highest market price of the equity symbol on the date
- low: The lowest recorded market price of the equity symbol on the date
- close: The closing recorded price of the equity symbol on the date
- symbol: Symbol of the listed company
- volume: Total traded volume of the equity symbol on the date
- date: Date of record

In this assignment, we will work on the stock prices dataset named "prices.csv". Task is to create a Neural Network to classify closing price for a stock based on some parameters.

In [245]:
# Initialize the random number generator
import random
random.seed(0)

# Ignore the warnings
import warnings
warnings.filterwarnings("ignore")

## Question 1

### Load the data
- load the csv file and read it using pandas
- file name is prices.csv

In [29]:
# run this cell to upload file using GUI if you are using google colab

from google.colab import files
files.upload()

ModuleNotFoundError: No module named 'google.colab'

In [ ]:
# run this cell to to mount the google drive if you are using google colab

from google.colab import drive
drive.mount('/content/drive/My Drive/')

In [246]:
import pandas as pd
data = pd.read_csv("prices.csv")

## Question 2

### Drop null
- Drop null values if any

In [247]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 851264 entries, 0 to 851263
Data columns (total 7 columns):
date      851264 non-null object
symbol    851264 non-null object
open      851264 non-null float64
close     851264 non-null float64
low       851264 non-null float64
high      851264 non-null float64
volume    851264 non-null float64
dtypes: float64(5), object(2)
memory usage: 45.5+ MB


In [248]:
data.isna().count()    ## no null values

date      851264
symbol    851264
open      851264
close     851264
low       851264
high      851264
volume    851264
dtype: int64

In [249]:
data.dropna()   

date symbol        open       close         low  \
0       2016-01-05 00:00:00   WLTW  123.430000  125.839996  122.309998   
1       2016-01-06 00:00:00   WLTW  125.239998  119.980003  119.940002   
2       2016-01-07 00:00:00   WLTW  116.379997  114.949997  114.930000   
3       2016-01-08 00:00:00   WLTW  115.480003  116.620003  113.500000   
4       2016-01-11 00:00:00   WLTW  117.010002  114.970001  114.089996   
5       2016-01-12 00:00:00   WLTW  115.510002  115.550003  114.500000   
6       2016-01-13 00:00:00   WLTW  116.459999  112.849998  112.589996   
7       2016-01-14 00:00:00   WLTW  113.510002  114.379997  110.050003   
8       2016-01-15 00:00:00   WLTW  113.330002  112.529999  111.919998   
9       2016-01-19 00:00:00   WLTW  113.660004  110.379997  109.870003   
10      2016-01-20 00:00:00   WLTW  109.059998  109.300003  108.320000   
11      2016-01-21 00:00:00   WLTW  109.730003  110.000000  108.320000   
12      2016-01-22 00:00:00   WLTW  111.879997  111.949997  110.190002   
13      2016-01-25 00:00:00   WLTW  111.320000  110.120003  110.000000   
14      2016-01-26 00:00:00   WLTW  110.419998  111.000000  107.300003   
15      2016-01-27 00:00:00   WLTW  110.769997  110.709999  109.019997   
16      2016-01-28 00:00:00   WLTW  110.900002  112.580002  109.900002   
17      2016-01-29 00:00:00   WLTW  113.349998  114.470001  111.669998   
18      2016-02-01 00:00:00   WLTW  114.000000  114.500000  112.900002   
19      2016-02-02 00:00:00   WLTW  113.250000  110.559998  109.750000   
20      2016-02-03 00:00:00   WLTW  113.379997  114.050003  109.639999   
21      2016-02-04 00:00:00   WLTW  114.080002  115.709999  114.080002   
22      2016-02-05 00:00:00   WLTW  115.120003  114.019997  109.709999   
23      2016-02-08 00:00:00   WLTW  113.300003  111.160004  110.459999   
24      2016-02-09 00:00:00   WLTW  111.169998  110.650002  109.639999   
25      2016-02-10 00:00:00   WLTW  106.730003  107.519997  106.360001   
26      2016-02-11 00:00:00   WLTW  105.629997  107.129997  104.110001   
27      2016-02-12 00:00:00   WLTW  108.559998  107.839996  107.070000   
28      2016-02-16 00:00:00   WLTW  109.110001  110.769997  107.010002   
29      2016-02-17 00:00:00   WLTW  110.830002  111.239998  107.970001   
...                     ...    ...         ...         ...         ...   
851234           2016-12-30    WAT  135.240005  134.389999  133.710007   
851235           2016-12-30    WBA   83.459999   82.760002   82.419998   
851236           2016-12-30    WDC   68.550003   67.949997   67.610001   
851237           2016-12-30    WEC   58.980000   58.650002   58.419998   
851238           2016-12-30    WFC   54.889999   55.110001   54.790001   
851239           2016-12-30    WFM   31.059999   30.760000   30.670000   
851240           2016-12-30    WHR  183.800003  181.770004  180.869995   
851241           2016-12-30     WM   71.269997   70.910004   70.750000   
851242           2016-12-30    WMB   30.940001   31.139999   30.889999   
851243           2016-12-30    WMT   69.120003   69.120003   68.830002   
851244           2016-12-30    WRK   51.840000   50.770000   50.529999   
851245           2016-12-30     WU   21.840000   21.719999   21.600000   
851246           2016-12-30     WY   30.450001   30.090000   29.950001   
851247           2016-12-30    WYN   76.849998   76.370003   76.180000   
851248           2016-12-30   WYNN   87.099998   86.510002   85.570000   
851249           2016-12-30    XEC  136.520004  135.899994  135.309998   
851250           2016-12-30    XEL   41.000000   40.700001   40.560001   
851251           2016-12-30     XL   37.360001   37.259998   37.060001   
851252           2016-12-30   XLNX   61.090000   60.369999   60.020000   
851253           2016-12-30    XOM   90.029999   90.260002   90.010002   
851254           2016-12-30   XRAY   58.290001   57.730000   57.540001   
851255           2016-12-30    XRX    8.720000    8.730000    8.700000   
851256           2016-12-30

### Drop columns
- Now, we don't need "date", "volume" and "symbol" column
- drop "date", "volume" and "symbol" column from the data


In [250]:
df = data.iloc[:,2:6]

## Question 3

### Print the dataframe
- print the modified dataframe

In [251]:
df

open       close         low        high
0       123.430000  125.839996  122.309998  126.250000
1       125.239998  119.980003  119.940002  125.540001
2       116.379997  114.949997  114.930000  119.739998
3       115.480003  116.620003  113.500000  117.440002
4       117.010002  114.970001  114.089996  117.330002
5       115.510002  115.550003  114.500000  116.059998
6       116.459999  112.849998  112.589996  117.070000
7       113.510002  114.379997  110.050003  115.029999
8       113.330002  112.529999  111.919998  114.879997
9       113.660004  110.379997  109.870003  115.870003
10      109.059998  109.300003  108.320000  111.599998
11      109.730003  110.000000  108.320000  110.580002
12      111.879997  111.949997  110.190002  112.949997
13      111.320000  110.120003  110.000000  114.629997
14      110.419998  111.000000  107.300003  111.400002
15      110.769997  110.709999  109.019997  112.570000
16      110.900002  112.580002  109.900002  112.970001
17      113.349998  114.470001  111.669998  114.589996
18      114.000000  114.500000  112.900002  114.849998
19      113.250000  110.559998  109.750000  113.860001
20      113.379997  114.050003  109.639999  114.639999
21      114.080002  115.709999  114.080002  116.320000
22      115.120003  114.019997  109.709999  116.489998
23      113.300003  111.160004  110.459999  113.300003
24      111.169998  110.650002  109.639999  112.110001
25      106.730003  107.519997  106.360001  112.110001
26      105.629997  107.129997  104.110001  109.260002
27      108.559998  107.839996  107.070000  109.430000
28      109.110001  110.769997  107.010002  111.300003
29      110.830002  111.239998  107.970001  112.110001
...            ...         ...         ...         ...
851234  135.240005  134.389999  133.710007  135.300003
851235   83.459999   82.760002   82.419998   83.620003
851236   68.550003   67.949997   67.610001   69.400002
851237   58.980000   58.650002   58.419998   59.119999
851238   54.889999   55.110001   54.790001   55.360001
851239   31.059999   30.760000   30.670000   31.299999
851240  183.800003  181.770004  180.869995  184.289993
851241   71.269997   70.910004   70.750000   71.500000
851242   30.940001   31.139999   30.889999   31.650000
851243   69.120003   69.120003   68.830002   69.430000
851244   51.840000   50.770000   50.529999   51.840000
851245   21.840000   21.719999   21.600000   21.900000
851246   30.450001   30.090000   29.950001   30.450001
851247   76.849998   76.370003   76.180000   76.970001
851248   87.099998   86.510002   85.570000   87.449997
851249  136.520004  135.899994  135.309998  137.559998
851250   41.000000   40.700001   40.560001   41.070000
851251   37.360001   37.259998   37.060001   37.419998
851252   61.090000   60.369999   60.020000   61.480000
851253   90.029999   90.260002   90.010002   90.699997
851254   58.290001   57.730000   57.540001   58.360001
851255    8.720000    8.730000    8.700000    8.800000
851256   49.980000   49.520000   49.360001   50.000000
851257   38.720001   38.669998   38.430000   39.000000
851258   63.930000   63.330002   63.160000   63.939999
851259  103.309998  103.199997  102.849998  103.930000
851260   43.070000   43.040001   42.689999   43.310001
851261   53.639999   53.529999   53.270000   53.740002
851262   44.730000   45.450001   44.410000   45.590000
851263   54.200001   53.630001   53.389999   54.480000

[851264 rows x 4 columns]

### Get features and label from the dataset in separate variable
- Let's separate labels and features now. We are going to predict the value for "close" column so that will be our label. Our features will be "open", "low", "high"
- Take "open" "low", "high" columns as features
- Take "close" column as label

In [252]:
X = df.drop("close",axis="columns")
X.head()

open         low        high
0  123.430000  122.309998  126.250000
1  125.239998  119.940002  125.540001
2  116.379997  114.930000  119.739998
3  115.480003  113.500000  117.440002
4  117.010002  114.089996  117.330002

In [253]:
y = df.iloc[:,1:2]
y.head()

close
0  125.839996
1  119.980003
2  114.949997
3  116.620003
4  114.970001

## Question 4

### Create train and test sets
- Split the data into training and testing

In [254]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

## Question 5

### Scaling
- Scale the data (features only)
- Use StandarScaler

In [255]:
from sklearn.preprocessing import StandardScaler

# Define the scaler 
scaler = StandardScaler().fit(X_train)

# Scale the train set
X_train = scaler.transform(X_train)

# Scale the test set
X_test = scaler.transform(X_test)

## Question 6

### Convert data to NumPy array
- Convert features and labels to numpy array

In [256]:
import numpy as np

In [257]:
y_train=np.array(y_train)
y_train

array([[62.98    ],
       [10.4     ],
       [73.060003],
       ...,
       [51.779999],
       [47.900002],
       [73.989998]])

In [258]:
y_test = np.array(y_test)
y_test

array([[56.990002],
       [12.42    ],
       [10.92    ],
       ...,
       [51.59    ],
       [69.260002],
       [73.160004]])

In [259]:
X_train.shape

(595884, 3)

In [260]:
X_test.shape

(255380, 3)

In [261]:
y_train.shape

(595884, 1)

In [262]:
y_test.shape

(255380, 1)

In [263]:
X_train = X_train.reshape(X_train.shape[0],X_train.shape[1],1)
print("X_train",X_train)
X_test = X_test.reshape(X_test.shape[0],X_test.shape[1],1)
print("X_test",X_test)

X_train [[[-0.09066067]
  [-0.08749153]
  [-0.09026979]]

 [[-0.72185845]
  [-0.72071592]
  [-0.72065945]]

 [[ 0.03814548]
  [ 0.03322552]
  [ 0.03312362]]

 ...

 [[-0.2507178 ]
  [-0.24636758]
  [-0.23132448]]

 [[-0.28256286]
  [-0.27672687]
  [-0.2747712 ]]

 [[ 0.04788915]
  [ 0.04282527]
  [ 0.03971722]]]
X_test [[[-0.1687286 ]
  [-0.16248968]
  [-0.16892133]]

 [[-0.69916289]
  [-0.69911645]
  [-0.69605141]]

 [[-0.71223363]
  [-0.71207613]
  [-0.71218204]]

 ...

 [[-0.2346764 ]
  [-0.23616786]
  [-0.23473901]]

 [[-0.01128568]
  [-0.01105338]
  [-0.00902798]]

 [[ 0.03125365]
  [ 0.03322547]
  [ 0.02264461]]]


## Question 7

### Define Model
- Initialize a Sequential model
- Add a Flatten layer
- Add a Dense layer with one neuron as output
  - add 'linear' as activation function


In [264]:
# Using Tensorflow Keras instead of the original Keras



from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten

# define the model architecture

# Initialize the constructor
model = Sequential()

# Add an input layer 
#model.add(Dense(12, input_shape=(4,)))

# Add one hidden layer 
model.add(Flatten())

# Add an output layer 
model.add(Dense(1, activation='linear'))

## Question 8

### Compile the model
- Compile the model
- Use "sgd" optimizer
- for calculating loss, use mean squared error

In [265]:
model.compile(loss='mean_squared_error',
              optimizer='sgd')

## Question 9

### Fit the model
- epochs: 50
- batch size: 128
- specify validation data

In [266]:
history = model.fit(X_train, y_train, validation_data = (X_test,y_test),epochs=50, batch_size=128)

Train on 595884 samples, validate on 255380 samples
Epoch 1/50
595884/595884 [==============================] - 8s 14us/sample - loss: 40.7937 - val_loss: 0.9533
Epoch 2/50
595884/595884 [==============================] - 7s 12us/sample - loss: 0.9811 - val_loss: 0.9719
Epoch 3/50
595884/595884 [==============================] - 7s 12us/sample - loss: 0.9741 - val_loss: 0.9735
Epoch 4/50
595884/595884 [==============================] - 7s 11us/sample - loss: 0.9666 - val_loss: 0.9393
Epoch 5/50
595884/595884 [==============================] - 8s 13us/sample - loss: 0.9624 - val_loss: 0.9257
Epoch 6/50
595884/595884 [==============================] - 7s 11us/sample - loss: 0.9541 - val_loss: 0.9161
Epoch 7/50
595884/595884 [==============================] - 7s 12us/sample - loss: 0.9493 - val_loss: 0.9238
Epoch 8/50
595884/595884 [==============================] - 7s 11us/sample - loss: 0.9416 - val_loss: 0.9048
Epoch 9/50
595884/595884 [==============================] - 7s 11us/sample 

## Question 10

### Evaluate the model
- Evaluate the model on test data

In [267]:
model.evaluate(X_test, y_test)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



0.7341381271683308

In [268]:
y_pred=model.predict(X_test)
y_pred

array([[56.983585],
       [12.3386  ],
       [11.129799],
       ...,
       [51.156464],
       [70.065094],
       [73.29221 ]], dtype=float32)

### Manual predictions
- Test the predictions on manual inputs
- We have scaled out training data, so we need to transform our custom inputs using the object of the scaler
- Example of manual input: [123.430000,	122.30999, 116.250000]

In [278]:
input_data=[[123.430000, 122.30999, 116.250000]]
scaled_input= scaler.transform(input_data)
scaled_input
#scaled_input = scaled_input.reshape(scaled_input.shape[0],1)
model.predict(scaled_input)

array([[119.648895]], dtype=float32)

# Build a DNN

### Collect Fashion mnist data from tf.keras.datasets 

In [232]:
%matplotlib inline


import tensorflow as tf

### Change train and test labels into one-hot vectors

In [292]:
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.fashion_mnist.load_data()

number = 10 


In [280]:
import numpy as np
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [281]:
y_train = tf.keras.utils.to_categorical(y_train, number)   # Converting the target into categorical which is stored as numeric
y_test = tf.keras.utils.to_categorical(y_test, number)     # Keras converst these into 1-hot coded vectors as these are lables


print ('Train size:', x_train.shape[0])
print ('Test size:', x_test.shape[0])

Train size: 60000
Test size: 10000


In [282]:
y_train                 #One hot encoded vector

array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [283]:
y_test

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

### Build the Graph

### Initialize model, reshape & normalize data

In [284]:
model = Sequential()
model.add(tf.keras.layers.Reshape((784,), input_shape = (28,28,)))
model.add(tf.keras.layers.BatchNormalization())

### Add two fully connected layers with 200 and 100 neurons respectively with `relu` activations. Add a dropout layer with `p=0.25`

In [285]:
from tensorflow.keras.layers import Dropout
model.add(Dense(200, activation='relu'))   #First hidden layer of 784  neurons, each neuron takes input 
                                                               # vector of size 784



model.add(Dense(100, activation='relu'))  

model.add(Dropout(0.25))



### Add the output layer with a fully connected layer with 10 neurons with `softmax` activation. Use `categorical_crossentropy` loss and `adam` optimizer and train the network. And, report the final validation.

In [286]:
model.add(Dense(10, activation='softmax'))


In [287]:
model.compile(loss="categorical_crossentropy", optimizer = "adam", metrics=["accuracy"])

In [288]:
#model.fit(x_train,y_train, epochs = 10, batch_size= 32)
model.fit(x_train, y_train,
                    batch_size=32,
                    epochs=10)

Train on 60000 samples
Epoch 1/10
60000/60000 [==============================] - 10s 164us/sample - loss: 0.5096 - accuracy: 0.8177
Epoch 2/10
60000/60000 [==============================] - 7s 111us/sample - loss: 0.3935 - accuracy: 0.8572
Epoch 3/10
60000/60000 [==============================] - 7s 119us/sample - loss: 0.3618 - accuracy: 0.8683
Epoch 4/10
60000/60000 [==============================] - 7s 112us/sample - loss: 0.3352 - accuracy: 0.8777
Epoch 5/10
60000/60000 [==============================] - 7s 119us/sample - loss: 0.3183 - accuracy: 0.8829
Epoch 6/10
60000/60000 [==============================] - 8s 126us/sample - loss: 0.3014 - accuracy: 0.8889
Epoch 7/10
60000/60000 [==============================] - 9s 147us/sample - loss: 0.2866 - accuracy: 0.8932
Epoch 8/10
60000/60000 [==============================] - 8s 127us/sample - loss: 0.2727 - accuracy: 0.8969
Epoch 9/10
60000/60000 [==============================] - 8s 133us/sample - loss: 0.2661 - accuracy: 0.9007
Epoc

In [289]:
model.evaluate(x_test,y_test)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.34804484552145004, 0.889]